[phases.setup]
nixPkgs = [
    'php82',
    'php82Extensions.intl',
    'php82Extensions.zip', 
    'php82Extensions.pdo_mysql',
    'php82Extensions.gd',
    'php82Extensions.curl',
    'php82Extensions.mbstring',
    'php82Extensions.xml',
    'php82Extensions.bcmath',
    'nodejs'
]

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-dev --ignore-platform-reqs'
]

[phases.build]
cmds = [
    'php artisan config:cache || true',
    'php artisan route:cache || true'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'