[phases.setup]
nixPkgs = ['php82', 'php82Extensions.intl', 'php82Extensions.zip', 'php82Extensions.pdo_mysql', 'nodejs']

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev']

[phases.build]
cmds = [
    'php artisan config:cache',
    'php artisan route:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'